spring:
  profiles:
    active: local
    default: local
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:db/data.sql

springdoc:
  version: 0.0.1
  title: MoneyLog API Documentation
  description: 머니로그 API 명세서
  termsOfService: piopoi
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match: /api/**
  packagesToScan: com.moneylog.api
  swagger-ui:
    try-it-out-enabled: false
    path: /swagger-ui
  api-docs:
    path: /api-docs
