spring:
  profiles:
    active: local
    default: local
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:db/data.sql
